name: Code analysis with Codacy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@master

